overrides:
  '@libp2p/gossipsub': 16.1.0
  '@le-space/orbitdb-identity-provider-webauthn-did': 0.3.1
  'orbitdb-relay>@orbitdb/core': 4.0.0
  react: 19.2.6
  react-dom: 19.2.6
  '@ipshipyard/node-datachannel': npm:node-datachannel@0.29.0
peerDependencyRules:
  allowedVersions:
    '@le-space/orbitdb-access-controller-delegated-todo>@le-space/orbitdb-identity-provider-webauthn-did': 0.3.1
    '@le-space/orbitdb-access-controller-delegated-todo>@orbitdb/core': 4.0.0
onlyBuiltDependencies:
  - esbuild
  - node-datachannel
  - "@tailwindcss/oxide"
  - cbor-extract
  - classic-level
minimumReleaseAgeExclude:
  - '@le-space/*'
  - orbitdb-relay
allowBuilds:
  "@tailwindcss/oxide": true
  cbor-extract: true
  classic-level: true
  esbuild: true
  node-datachannel: true
